# Generated by Django 3.1 on 2020-08-09 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(verbose_name='품목ID')),
                ('review_content', models.TextField(verbose_name='내용')),
                ('username', models.CharField(max_length=100, verbose_name='성명')),
                ('review_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, verbose_name='품명')),
                ('item_type', models.CharField(choices=[('Main shop', '메인Food'), ('Side Menu', 'Side Menu'), ('Others', 'Cleaner')], max_length=10, verbose_name='타입')),
                ('item_mainimg', models.FileField(upload_to='uploaded/', verbose_name='매인IMG')),
                ('item_detailimg', models.FileField(upload_to='uploaded/', verbose_name='세부IMG')),
                ('item_basketimg', models.FileField(upload_to='uploaded/', verbose_name='장바구니IMG')),
                ('item_price', models.IntegerField(default=0, verbose_name='가격')),
                ('item_dcprice', models.IntegerField(blank='True', default=0, verbose_name='DC가격')),
                ('item_totalcount', models.IntegerField(default=0, verbose_name='총량')),
                ('item_salecount', models.IntegerField(default=0, verbose_name='판매수량')),
                ('item_remaincount', models.IntegerField(default=100, verbose_name='잔여량')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_name', models.CharField(max_length=100, verbose_name='접수자명')),
                ('delivery_phone', models.CharField(max_length=100, verbose_name='전화')),
                ('delivery_zipcode', models.CharField(max_length=100, verbose_name='우편번호')),
                ('delivery_addr1', models.CharField(max_length=100, verbose_name='주소1')),
                ('delivery_addr2', models.CharField(blank='True', max_length=100, verbose_name='주소2')),
                ('delivery_request', models.CharField(blank='True', max_length=100, verbose_name='요구사항')),
                ('pay_type', models.CharField(max_length=100, verbose_name='지불방법')),
                ('pay_account', models.CharField(blank='True', max_length=100, verbose_name='계좌번호')),
                ('member_id', models.IntegerField(verbose_name='멤버ID')),
                ('item_name', models.CharField(max_length=100, verbose_name='상품명')),
                ('order_count', models.IntegerField(verbose_name='품목갯수')),
                ('item_id', models.IntegerField(verbose_name='멤버ID')),
                ('total_price', models.IntegerField(verbose_name='가격')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, verbose_name='품명')),
                ('basket_count', models.IntegerField(verbose_name='판매수량')),
                ('member_id', models.IntegerField(verbose_name='멤버ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.item', verbose_name='상품ID')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
